version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - keycloak
    environment:
      KEYCLOAK_SERVER_URL: http://localhost:8080/
      KEYCLOAK_REALM: flask-app
      KEYCLOAK_CLIENT_ID: todo-app
      KEYCLOAK_CLIENT_SECRET: 1NTRNSl36MsB2RGk45CmsvhqrTKHdrn3 
    networks:
      - backend

  keycloak:
    image: jboss/keycloak:15.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
